# Site settings
title: Ryan T. Skelskey | Blog
email: rtskelskey2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Ryan Skelskey and I'll be blogging about the businesses I work with: Tailor Made SF - Mobile Tailoring | The Hydrilla - Design and Demolition | Head Lands Productions - Video Production. Check out my Affiliates Page for more info.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
